### ISSUE TITLE
Possible improvements?

### ISSUE THREAD

**Issue by AriaFallah** [AriaFallah/mobx-store#1]
@mweststrate not really sure if this is an abuse of mobx since I'm using the private methods. I was wondering if you could take a look.

I'm using the `reportChanged` functionality to make it work

```js
db.object[key].$mobx.atom.reportChanged()
```

**Comment by mweststrate** [comment]
Using internals is bad sign indeed :)

It is not entirely clear to me whey changes are reported, I would have expected `reportObserved` in the `chain` function? Or is this because users are allowed to modify data returned from a chain? Otherwise I think you can base your chain on just `db.object[key].slice()`, which gives a defensive copy and makes sure your autoruns are re-run when the collection is changed again in the future.

**Comment by AriaFallah** [comment]
@mweststrate Well the original implementation of the library is here: https://github.com/typicode/lowdb

And the idea is that you can both read and write to the DB by chaining lodash methods

```js
// Read Example
db('posts')
  .chain()
  .filter({published: true})
  .sortBy('views')
  .take(5)
  .value()

// Write Example
db('posts')
  .chain()
  .find({ title: 'low!' })
  .assign({ title: 'hi!'})
  .value()
```

My problem with the original library was that I couldn't call the lodash methods on an `Observable Array` so I wanted a way to be able to modify the underlying collection with lodash methods while also keeping the array emitting the observable events.

Does `db.object[key].slice()` allow for this?

**Comment by mweststrate** [comment]
Ok thanks for the info, the use case is now clear to me. ObservableArrays are sadly no real arrays until ES6 proxies will become wide available, as it is not possible in ES5 to customize real arrays. Real arrays simply cannot be observed. Slicing turns a observable array back into a real array, but as you will have noticed, it won't "write through", meaning that this approach is only viable for read operations. 

I have to think about this a bit more, but these directions might be interesting:

1. provide the whole chain api as smaller wrapper functions around the backing observable array. If there are many functions allowed this could be quite some work although all the read api's could be wrapped generically.
2. Trick lodash into thinking that ObservableArrays are real arrays. That should work fine if it uses normal array methods, but won't work if it uses methods from Array.prototype.
3. Let the chain start with a sliced copy, and copy it back to the original array at the end of the chain. But I doubt whether you can reliably determine that moment.

Probably not very satisfying, but I hope that answers the question.

**Comment by AriaFallah** [comment]
I think I already have approach #1 working. Would you mind taking a look at the source, and letting me know if my implementation is a good one?

I just commented all of it so it's easier to understand as well.

**Comment by mweststrate** [comment]
Hmm, since you have the checksum anyway, you could make it maybe even cleaner by slicing, after the chain check whether it has changed, if if that is the case use `.replace(changedCollection)` on the observable array. The slice will make sure that `reportObserved()` is called (or maybe that should not happen always?), and `replace` will automatically invoke `reportChanged` itself.

I think btw that there is some consistency check to see whether the internal values are not changed from the outside, I would have to double check that. (and verify whether those are really needed)

**Comment by AriaFallah** [comment]
@mweststrate I think this is a good idea, but I have two concerns, which really both address the same thing.

Wouldn't this approach be much less performant just to avoid calling the private methods?

1. I use slice() when I already have direct access to the underlaying data.
2. I mutate that sliced array and then I use that sliced array with replace() to mutate the underlying data. I would do double the work.

The advantage is that I don't need to call the reporting methods, but is it really such a bad thing if it's done properly?

My new question would be what's the downside to explicitly using the $mobx private methods for observation?

**Comment by mweststrate** [comment]
@AriaFallah the trouble you might run into from changing internal semantics might be much bigger then the possible performance overhead. In these kind of situations (accessing private internals from other libs) it holds more than ever: premature optimization is the root of all evil. Privates are for a reason private; they might change between any version. They might be renamed, or even be minified in minified builds. I simply cannot guarantee future compatibility of private methods.

Besides that, it won't suprise me that `slice` + `replace` is actually _faster_ in most common cases. A full array slice is a really cheap operation because browsers can very efficiently clone a complete collection at once. Besides that, after slicing, each read is slightly cheaper as reading from observable arrays is actually a little more expensive (each property access will run `reportObserved`) and with slicing that happens only once.

The same holds for `replace`, replacing a full observable array has almost the same overhead as just pushing a single item to it. Both run `reportChanged` and emit a single event. So replacing only once might again be cheaper than applying multiple small mutations in the chain.

**Comment by AriaFallah** [comment]
@mweststrate I came to the same conclusion after I edited my question about 50 times 😅 .

I think what I said above matches what you just said

> So really I think the conclusion I've reached is to explicitly call reportObserved() because sometimes I want to report an observation without creating a new copy of the array, but to use replace() instead of reportChanged() so I can adhere to whatever you're doing behind the scenes.

I think the only problem now is the figuring out implementation of using `replace()`.

Thank you for all your help.

**Comment by AriaFallah** [comment]
@mweststrate Seems to be working now with the public API 😄 . Thanks.

**Comment by mweststrate** [comment]
Cool!

Op wo 20 apr. 2016 om 00:50 schreef Aria Fallah <notifications@github.com>:
